apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-sts-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{ if .Values.resc.config.dbConnectionString }}
  DB_CONNECTION_STRING: "{{ .Values.resc.config.dbConnectionString | b64enc }}"
  {{ end }}
  {{ if and (eq .Values.useKubernetesSecret "true") (.Values.resc.config.dbPass) }}
  MSSQL_PASSWORD: "{{ .Values.resc.config.dbPass | b64enc }}"
  {{ end }}