apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-secret-scanner-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{ if .Values.config.rabbitmq_queue }}
  RABBITMQ_QUEUE: "{{ .Values.config.rabbitmq_queue }}"
  {{ end }}
  {{ if .Values.config.force_base_scan }}
  FORCE_BASE_SCAN: "{{ .Values.config.force_base_scan }}"
  {{ end }}
  {{ if .Values.image.gitleaks.binaryPath }}
  GITLEAKS_PATH: {{ .Values.image.gitleaks.binaryPath }}
  {{ else }}
  GITLEAKS_PATH: {{ .Values.global.rescSecretScanner.image.gitleaks.binaryPath }}
  {{ end }}
  {{ if .Values.config.debug_value }}
  DEBUG_MODE: "{{ .Values.config.debug_value }}"
  {{ end }}
  {{ if .Values.config.vcs_instance_file_path }}
  VCS_INSTANCES_FILE_PATH: "{{ .Values.config.vcs_instance_file_path }}"
  {{ end }}
